FROM node:18-alpine

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm i --fetch-timeout=3000000

COPY --chown=node:node ./ ./

CMD [ "npm","run","dev" ]
