name: Deploy Multicontainer Docker App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t shubhamjr/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true shubhamjr/react-test npm test
      - run: docker build -t shubhamjr/multi-client ./client
      - run: docker build -t shubhamjr/multi-nginx ./nginx
      - run: docker build -t shubhamjr/multi-server ./server
      - run: docker build -t shubhamjr/multi-worker ./worker

      name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: shubhamjr/multi-client:latest
          context: ./nginx
          push: true
          tags: shubhamjr/multi-nginx
          context: ./server
          push: true
          tags: shubhamjr/multi-server ./server
          context: ./worker
          push: true
          tags: shubhamjr/multi-worker ./worker

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-react
      #     environment_name: Dockerreact-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-629074341281
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip